name: Release

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'
          cache: 'yarn'

      - name: Debug environment
        run: |
          echo "Current shell: $SHELL"
          echo "Shell exists: $(which sh)"
          echo "Directory structure:"
          ls -la /
          echo "Environment variables:"
          env | sort
          echo "Available shells:"
          cat /etc/shells || echo "Cannot read /etc/shells"
          echo "Testing shell execution:"
          bash -c "echo 'Bash works'"
          sh -c "echo 'Sh works'" || echo "Sh does not work"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends zip git python3 make g++ build-essential libx11-dev libx11-xcb-dev libxkbfile-dev libnotify-bin libkrb5-dev
          sudo ln -sf /usr/bin/python3 /usr/bin/python
          echo "Verifying shell after installation:"
          which sh
          ls -la /bin/sh

      - name: Install dependencies
        run: |
          echo "Using shell: $SHELL"
          yarn install --frozen-lockfile

      - name: Create symbolic link for sh
        run: |
          echo "Creating symbolic link for sh"
          sudo ln -sf /bin/bash /bin/sh
          echo "Verifying sh link:"
          ls -la /bin/sh

      - name: Build project
        run: |
          echo "Using shell: $SHELL"
          # Run the build script directly
          node build.js

      - name: Prepare demo
        run: |
          echo "Using shell: $SHELL"
          yarn prepare-demo

      - name: Create zip archive
        run: |
          echo "Using shell: $SHELL"
          mkdir -p release
          zip -r release/vscode-web.zip demo

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-web-release
          path: release/vscode-web.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: release/vscode-web.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
